
name: Continuous Integration Lint
on:
  pull_request:
    branches:
      - main
        - develop

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

